apiVersion: v1
kind: Service
metadata:
  labels:
    run: pinepain-grav
  name: pinepain-grav
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 30080
    protocol: TCP
    targetPort: 30080
  selector:
    run: pinepain-grav
  type: NodePort
